Store
bem/bem-forum pull request #27
Opened 2017-03-25 15:14 UTC by skad0

2017-03-25 22:06 UTC, tadatuta requested changes

2017-03-25 22:06 UTC, tadatuta commented on common.blocks/api-request/api-request.deps.js
> +        { block: 'page', mod: 'store', val: true },
чего не `{ mods: { store: true } }`?

2017-03-25 22:06 UTC, tadatuta commented on common.blocks/api-request/api-request.js
> +     * @param {*} context - контекст выполнения колбеков (deprecated, instead use arrow functions)
у нас клиент без бабеля, так что пока без arrow functions, стало быть нет смысла обзывать аргумент deprecated

2017-03-25 22:06 UTC, tadatuta commented on common.blocks/api-request/api-request.js
> +     * Делает fetch запрос в АПИ
было бы круто сразу перевести JSDoc-и на англ

2017-03-25 22:06 UTC, tadatuta commented on common.blocks/api-request/api-request.md
> +<a name="module_api-request"></a>
а зачем этот якорь?

2017-03-25 22:06 UTC, tadatuta commented on common.blocks/fetch/fetch.js
> +/* borschik:include:../../node_modules/whatwg-fetch/fetch.js */
странно, что линтер не ругнулся на отсутствие new line at EOF

2017-03-25 22:06 UTC, tadatuta commented on common.blocks/issue/issue.js
> +            .then(function(response) { return response.text() })
нет `;`

вроде же были линтеры включены o_0

2017-03-25 22:06 UTC, tadatuta commented on common.blocks/promise/promise.js
> +/* borschik:include:../../node_modules/es6-promise/dist/es6-promise.auto.js */
new line at EOF

2017-03-25 22:06 UTC, tadatuta commented on common.blocks/issue/issue.js
> +            .then(function(response) { return response.text() })
а не сделать ли, чтобы `request()` и `request.*()` делали `response.text()` под капотом, а для кейсов, когда нужны заголовки предоставлять `request.raw()`?

// cc @birhoff

2017-03-25 22:06 UTC, tadatuta commented on package.json
> +    "json-superstring": "^1.0.0",
не используется?

2017-03-25 23:05 UTC, birhoff commented on common.blocks/issue/issue.js
> +            .then(function(response) { return response.text() })
Лучше сделать опцию, которая будет примерно называться responseParser: 'json|text|no-parser'.

А по дефолту надо не `.text()` брать, а делать эвристику на заголовок `Content-Type`.

2017-03-25 23:07 UTC, birhoff commented on common.blocks/api-request/api-request.js
> +    request._basePath = '/api/';
Это не префикс приложения, а API префикс

2017-03-25 23:08 UTC, birhoff commented on common.blocks/promise/promise.js
> +/* borschik:include:../../node_modules/es6-promise/dist/es6-promise.auto.js */
Заведите задачу донастроить линтер

2017-03-25 23:11 UTC, birhoff commented on common.blocks/store/store.js
> +        }
Ребят, а как это вообще работает?
В `inited` используется `data` без `underscore`. А тут `this._data`.
Зачем еще и в параметры складывать это?

Кстати если это `store`, то давайте и API соответствующее, надо сделать не `getData`, а `getState`.

2017-03-25 23:12 UTC, birhoff commented on package.json
> +    "whatwg-fetch": "^2.0.3"
Кажется что этому место в `devDependencies`, так как используется при сборке.

2017-03-25 23:13 UTC, birhoff commented on common.blocks/api-request/api-request.js
> +], function(provide, $, Querystring, store) {
`store` у вас класс, не инстанс.

2017-03-25 23:14 UTC, birhoff commented on common.blocks/api-request/api-request.js
> +        }
102-108 Вы не будете использовать

2017-03-26 10:07 UTC, skad0 commented on common.blocks/store/store.js
> +        }
@birhoff это не обязательно redux-store, почему бы ему не быть stateless?

2017-03-26 10:11 UTC, skad0 commented
@tadatuta

2017-03-26 23:32 UTC, tadatuta approved these changes

2017-03-26 23:32 UTC, merged