#10: Support post removal
bem/bem-forum pull request #28
Opened 2017-03-25 15:52 UTC by dustyo-O

@skad0 @tadatuta

2017-03-25 16:05 UTC, dustyo-O commented
this solves #10

2017-03-25 22:07 UTC, tadatuta commented
тесты упали:

```
Deps validation error at common.blocks/issue/issue.deps.js :
Invalid type (boolean) in ".shouldDeps[4].mods.visible[0]": expected string
Deps validation error at common.blocks/issue/issue.deps.js :
Invalid type (boolean) in ".shouldDeps[4].mods.visible[1]": expected string
Deps validation error at common.blocks/issue/issue.deps.js :
Invalid type (boolean) in ".shouldDeps[5].mods.visible[0]": expected string
Deps validation error at common.blocks/issue/issue.deps.js :
Invalid type (boolean) in ".shouldDeps[5].mods.visible[1]": expected string
```

2017-03-25 22:24 UTC, tadatuta requested changes

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.bemtree.js
> +                    text: i18n(this.block, 'Delete'),
по негласной договоренности порядок ключей: `block`, `mods`, `mix`, `text`

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.bemtree.js
> +                    mods: { theme: 'islands', autoclosable: true, visible: false },
модификатор в значении `false` не имеет смысла

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.bemtree.js
> +            block: 'issue',
здесь и везде ниже вместо хардкода имени блока использовать `this.block` (можно закешировать заранее)

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.bemtree.js
> +                                    js: { number: issue.number }
поле `js` поднять перед `mix`

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.bemtree.js
> +                            mods: { theme: 'islands', size: 'm', visible: false },
false не имеет смысла

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.bemtree.js
> +                    mix: { block: 'issue', elem: 'delete-confirm-modal' },
есть желание, чтобы модал получился более универсальным: мог получать любой `msg` в качестве аргумента и рисовать да/нет. наверняка еще где-нибудь пригодится.

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.bemtree.js
> +                                    mix: { block: 'issue', elem: 'delete-modal-yes' },
кажется, что нет необходимости миксовать элементы, лучше сделать js-параметры

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.css
> +.issue__delete-modal-body .issue__delete-modal-yes,
тут точно нужна вложенность?

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.deps.js
> +            mods: { theme: 'islands', visible: [true, false], autoclosable: true }
значение `false` не имеет смысла

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.js
> +                var commentsElem = this.findChildElem('comments-button');
понимаю, что так было раньше, но лучше сразу везде, где можно заменить `findChildElem*` на `_elem*`

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.js
> +        event.preventDefault();
какую задачу здесь решает `preventDefault`?

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.js
> +        modal.setMod('visible', true);
`true` писать не обязательно

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.js
> +            if (response === 'ok') {
а если не ок, то что? :)

2017-03-25 22:24 UTC, tadatuta commented on common.blocks/issue/issue.js
> +            modalBody.setMod('visible', true);
тут бы какое-то пояснение для пользователя, что ничего такого не случилось

2017-03-25 22:24 UTC, tadatuta commented on server/controllers/gh.js
> +    makeIssueRemoveRequest(issueAddLabelRequestUrl).then(function() {
removeIssueRequest

2017-03-26 08:54 UTC, dustyo-O commented on common.blocks/issue/issue.bemtree.js
> +                                    mix: { block: 'issue', elem: 'delete-modal-yes' },
на это стили привязываем

2017-09-30 10:10 UTC, closed without merging