Mark and some improvements
bem/bem-forum pull request #29
Opened 2017-03-26 15:33 UTC by skad0

Я тут отребейзился от ветки со стором, ибо стопорило. Когда та вольется, эту обновлю.

2017-03-26 23:39 UTC, tadatuta requested changes

2017-03-26 23:39 UTC, tadatuta commented on server/router.js
> +        // passportGitHub.authenticate('github', { scope: ['repo'] }),
м?

2017-03-26 23:39 UTC, tadatuta commented on server/router.js
> +    // .patch('/api/:id(\\d+)/close', controllers.gh.markAsResolved)
не пригодилось?

2017-03-26 23:39 UTC, tadatuta commented on common.blocks/issue/issue.bemtree.js
> +                mods: { theme: 'islands', size: 'm', visible: false },
`visible: false` не имеет смысла

2017-03-26 23:39 UTC, tadatuta commented on common.blocks/issue/issue.js
> +                this._events(markResolved).on('mark-resolved-loading', this._onMarkResolvedLoading);
стоит зачейнить `this._events(markResolved)`

2017-03-26 23:39 UTC, tadatuta commented on package.json
>      "got": "^6.3.0",
чистый got все еще нужен?

2017-03-27 10:44 UTC, skad0 commented
:up:

2017-03-27 10:58 UTC, tadatuta approved these changes

2017-03-27 10:58 UTC, tadatuta commented on server/controllers/gh.js
> +        res.send('Ok').status(204);
вкусовщины ради давай инвертнем:
```js
res.status(204).send('ok');
```

2017-03-27 10:58 UTC, tadatuta commented on common.blocks/issue/_state/issue_state_closed.css
> +    .issue__mark-resolved, .issue__comments-button {
comments-button не нужно скрывать, если есть решение — типа в треде на исходный вопрос ответили, но общаться-то дальше можно

2017-03-27 10:58 UTC, tadatuta commented on common.blocks/issue/__mark-resolved/issue__mark-resolved.bemtree.js
> +        text: 'Проблема решена'
предлагаю заиспользовать иконку, а текст перенести в `title`

2017-03-28 20:43 UTC, tadatuta commented on package.json
> +    "bem-font-awesome": "^1.0.1",
это не то пальто. нужно https://github.com/tadatuta/bem-font-awesome-icons, чтобы не тянуть шрифты

2017-03-28 20:43 UTC, tadatuta commented on server/config.js
> +    org: 'skad0',
нет смысла это коммитить

2017-03-28 20:43 UTC, tadatuta commented on .borschik
> +    "paths": {
эти изменения не потребуются с bem-font-awesome-icons

2017-03-28 21:42 UTC, skad0 commented on server/config.js
> +    org: 'skad0',
там wip) просто коммитнул текущий стейт)

2017-03-28 21:43 UTC, skad0 commented on package.json
> +    "bem-font-awesome": "^1.0.1",
ого, не знал.
а чего на тайкуне его не заюзали?

2017-03-28 22:26 UTC, tadatuta commented on package.json
> +    "bem-font-awesome": "^1.0.1",
про это есть задача, нужно бы смигрировать

2017-03-30 13:41 UTC, skad0 commented
:up:
@tadatuta

2017-03-30 15:33 UTC, tadatuta approved these changes

2017-03-30 15:33 UTC, tadatuta commented on common.blocks/issue/__toggle-resolved/issue__toggle-resolved.bemtree.js
> +        title: 'Переключить между решено и не решено', // TODO: придумать что получше
```js
title: issue.state === 'closed' ? 'Переоткрыть' : 'Есть решение'
```

2017-03-30 15:34 UTC, skad0 commented on common.blocks/issue/__toggle-resolved/issue__toggle-resolved.bemtree.js
> +        title: 'Переключить между решено и не решено', // TODO: придумать что получше
в динамике шаблон на клиент придется тащить :-(

2017-03-30 16:28 UTC, merged