editing issue by authors
bem/bem-forum pull request #55
Opened 2017-07-04 04:08 UTC by LISBON11

2017-07-04 09:24 UTC, skad0 requested changes

2017-07-04 09:24 UTC, skad0 commented on common.blocks/add-form/_type/add-form_type_edit.js
> +            request(issueId, {
я думаю так делать не стоит, изначально блок не для этого задумывался и так получится копипаста.

Ты можешь взять за пример форму добавления поста, а у этого блока использовать его api и type_post (это не про метод передачи, а про форму для поста).

2017-07-04 09:24 UTC, skad0 commented on common.blocks/add-form/_type/add-form_type_edit.js
> +            request(issueId, {
Я думаю это должно быть так:
вставляешь формочку в шаблон issue, сабмит обрабатываешь в его js реализации.

2017-07-04 09:24 UTC, skad0 commented on common.blocks/add-form/add-form.bemtree.js
> +                            issueId: ctx.issueId
и тогда этого тоже не нужно

2017-07-04 09:24 UTC, skad0 commented on common.blocks/issue/issue.bemtree.js
> +                    mix: { block, elem: 'edit-button' },
вот это наверное кнопка которая в экшенах должна быть? чуть выше глянь есть elem соответствующий и уже с проверкой на пользователя

2017-07-04 09:24 UTC, skad0 commented on common.blocks/issue/issue.bemtree.js
> +                issue.user.login === data.userLogin ? {
давай везде по id проверять

2017-07-04 09:24 UTC, skad0 commented on common.blocks/issue/issue.js
> +    _onEditFormCompleated: function(e, data) {
completed

2017-07-04 09:24 UTC, skad0 commented on common.blocks/issue/issue.js
> +        var content = this.editForm.findChildBlock(Editor);
здесь ты завязываешь на реализацию другого блока, лучше в api блока сделай, например, _gatherData публичным и используй.

2017-07-04 09:24 UTC, skad0 commented on common.blocks/issue/issue.js
> +                this.editButton = this._elem('edit-button').findMixedBlock(Button) || '';
очень странно)

2017-07-04 09:24 UTC, skad0 commented on common.blocks/issue/issue.js
> +                this.editForm = this._elem('edit-form') || '';
почему так?

2017-07-04 09:24 UTC, skad0 commented on common.blocks/add-form/_type/add-form_type_edit.js
> +            request(issueId, {
а еще я не вижу тут у тебя использования простейшего валидирования, которое есть как раз в базовой реализации блока

2017-07-04 09:24 UTC, skad0 commented on common.blocks/issues/issues.bemtree.js
> +                userLogin: data.userLogin
если он у тебя прокидывается только для проверки на авторизацию, то он не нужен

2017-07-06 19:52 UTC, tadatuta commented
ветка конфликтует с мастером, нужно отребейзить

2017-07-08 19:47 UTC, tadatuta commented on common.blocks/form-wrapper/form-wrapper.js
> +    lazyInit: false,
?

2017-07-08 19:47 UTC, tadatuta commented on common.blocks/form-wrapper/form-wrapper.bemtree.js
> +block('form-wrapper').content()(node => {
сделать элементом
придумать название

2017-07-08 19:47 UTC, tadatuta commented on server/controllers/gh.js
> +    var type = req.params.type;
const

2017-07-08 19:47 UTC, tadatuta commented on server/controllers/gh.js
> +            case 'form':
распилить на 2 контроллера

2017-07-08 19:47 UTC, tadatuta commented on server/router.js
> +    .get('/:id(\\d+)/:type?', keepRetpath, controllers.gh.getIssue)
попробовать избавиться от type

2017-07-08 19:47 UTC, tadatuta commented on common.blocks/user/user.bemhtml.js
> +    return  {
сохранить декларативщину

2017-07-14 12:40 UTC, skad0 commented
Надо было отребейзится от мастера без мердж коммита.
И что за submodule bem-forum появился?

2017-07-14 12:43 UTC, skad0 commented on common.blocks/send-form/send-form.bemtree.js
> +            ctx.js.formType == 'issue' ? {
а почему завязка на js параметр не в клиентском коде?

@tadatuta Вообще непонятно что стало лучше, сейчас выглядит как костыль, из-за которого и дальше в коде костыли.

2017-07-14 12:43 UTC, skad0 commented on common.blocks/send-form/send-form.js
> +                this.params.formType == 'issue' ? this.showErrorMessage('Заполните все поля') :
сюда i18n надо

2017-07-14 12:44 UTC, skad0 commented on common.blocks/send-form/send-form.js
> +            if (this.params.formType == 'issue' ? emptyFields.length : emptyFields.length - 1) {
вообще жестко выглядит этот костыль, @tadatuta это точно рефакторинг был?

2017-07-14 12:44 UTC, skad0 commented on common.blocks/send-form/send-form.js
> +            this._events('submit-btn')
а чего на одной строке не поместилось?

2017-07-25 12:39 UTC, LISBON11 commented on common.blocks/issue/__edit-form/issue__edit-form.js
> +            request(e.bemTarget.params.issue.number, {
обрабатывать фейл

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/api-request/api-request.js
> +
expose `raw` instead of current `request()` and call `.then(function(response) { return response.text(); })` in request

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/comment/comment.css
> +        &_hidden {
get rid of extra styling

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/comment/comment.js
> +                this._elem('content').domElem.html(data.rawBody);
???

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/comment/comment.js
> +                lazyInit: false,
?

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/comments/comments.bemtree.js
> +                        mix: { block: 'add-form' },
form should be visible by default and its parent should decide on visibility

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/editing/editing.js
> +    const PageCreatePost = bemDom.declBlock(this.name, {
Editing

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/editing/editing.js
> +                inited: function() {
```js
_getDefaultParams: function() {
    return {
        apiUrls: {
            issue: {
                get: 'form/',
                edit: ''
            },
            comment: {
                get: 'issues/comments/',
                edit: 'issues/comments/'
            }
        },
        settings: {
            id: this.params.entityId,
            formType: this.params.formType
        }
    };
}
```

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/editing/editing.js
> +                                this._emit('insert' +
```js
this._emit(formType === 'issue' ? 'insertIssueForm' : 'insertCommentForm', formHtml);
```

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/editing/editing.js
> +                        formType.charAt(0).toUpperCase() + formType.slice(1), data);
+

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/editing/editing.js
> +                    this.sendForm.showErrorMessage('The' + formType + ' was not changed');
space

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/editing/editing.js
> +            this.sendForm = this.findChildBlock(SendForm);
```js
this.sendForm = this.findChildBlock(SendForm).setMod('loading');
```

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/editing/editing.js
> +            var postUrl = this.settings.formType === 'issue' ? 'create' : this.settings.id + '/comments';
```js
var isIssue = this.settings.formType === 'issue';
```

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/issue/issue.css
> +        &_hidden {
?

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/send-form/send-form.bemtree.js
> +            ctx.formType == 'issue' ? {
===

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/send-form/send-form.css
> +    display: none;
:)

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/send-form/send-form.js
> +                errorMessage: 'Заполните все поля'
i18n

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/send-form/send-form.js
> +        _getPreviewedBody: function() {
`_getPreviewBody`

2017-07-27 14:32 UTC, LISBON11 commented on common.blocks/send-form/send-form.js
> +        fromInfo: {
_getDefaultParams

```diff
- fromInfo
+ info
```

2017-07-27 14:32 UTC, LISBON11 commented on server/config.js
> +
remove

2017-07-27 14:32 UTC, LISBON11 commented on server/controllers/gh.js
> +        makeIssueRequest(issueRequestUrl, { token })
get rid of Promise.all

2017-07-27 14:32 UTC, LISBON11 commented on server/controllers/gh.js
> +    Promise.all([
```diff
- Promise.all
```

2017-07-27 14:32 UTC, LISBON11 commented on server/controllers/gh.js
> +function getComment(req, res) {
move common for `getIssue()` and `getComment()` to `_getData()`

2017-07-31 14:22 UTC, merged