fix token
bem/bem-forum pull request #60
Opened 2017-07-25 02:06 UTC by LISBON11

2017-07-25 09:41 UTC, skad0 requested changes

2017-07-25 09:41 UTC, skad0 commented on server/controllers/gh.js
> +        const token = getToken(req.user);
отступ не нужен

2017-07-25 10:03 UTC, tadatuta commented
так делать определенно не нужно

2017-07-25 10:35 UTC, AnyaTyu commented on server/controllers/gh.js
> +        const token = getToken(req.user);
почему бы не прикрутить линтеры сюда. С bem.info скопипастить например

2017-07-27 14:36 UTC, LISBON11 commented
https://github.com/cataria-rocks/cataria/blob/master/server/auth.js#L6-L13

2017-07-31 12:01 UTC, closed without merging